### PR TITLE
Adding support for copy to clipboard button

### PR DESCRIPTION
**Pull request by lirantal**
- Added the `angular2-clipboard` dependency
- Enabled support for the copy button

### CODE REVIEW

**Comment by lirantal** [comment]
cc @IdanCo please review

**Comment by IdanCo** [comment]
It can't be so simple! you're cheating!

anyway, looks great.

**Comment by lirantal** [comment]
Awesome. Thanks for looking into it!

**Comment by lirantal** [comment]
Guess I forgot to merge this in :)

**Pull request merged**
